language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
env:
  - SUITE=lint
  - SUITE=unit
  - SUITE=versioned
matrix:
  exclude:
    - node_js: "6"
      env: SUITE=lint
    - node_js: "7"
      env: SUITE=lint
    - node_js: "8"
      env: SUITE=lint
    - node_js: "9"
      env: SUITE=lint
services:
  - mysql
script: npm run $SUITE
